# Generated by Django 5.1.6 on 2026-02-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liters", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("odometer_km", models.PositiveIntegerField()),
                ("station_name", models.CharField(blank=True, max_length=150)),
                ("fuel_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-fuel_date"],
            },
        ),
    ]
